### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexmartinfr**
Small typos fixed and legibility improvements.

Feel free to adjust / reject what you don't like!

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by alexmartinfr** [comment]
You're welcome!

Also, link to the "Muli" font seems to be dead:
https://fonts.google.com/specimen/Muli

I've found one named Mulish, but not sure it's the good one.

@driesvints @caneco

**Comment by caneco** [comment]
Apparently it's true… 
https://github.com/google/fonts/pull/2504

**Nice catch!**

**Comment by driesvints** [comment]
Fixed it. Thanks!

**Comment by caneco** [comment]
> Small typos fixed and legibility improvements.

Me and my _engrish_ 😅

**Comment by alexmartinfr** [comment]
These were really minor corrections 😉
Anyway, I love proof-reading so feel free to ask anytime!

**Pull request merged**
